modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraftiv"
version="4.2.2"
displayName="LoloCraftIV"
credits="2022 Copyright Fox Inc. Germany"
displayURL="http://lolocraft.derlolo.de/lolocraft/lolocraft-iv/"
logoFile="logo.png"
authors="DerLoloHD (with help from TheXBOXPlayz and Smash_Vini)"
description='''
The New Adventure in a new LoloCraft Mod
'''

[[dependencies.lolocraftiv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




