modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraftiv"
version="Alpha 0.0.1"
displayName="LoloCraftIV"
credits="Thanks to TheXBOXPlayz for the better English in this Mod <3"
displayURL="https://mclolocraft.jimdosite.com/LoloCraftIV"
logoFile="logo.png"
authors="DerLoloHD"
description='''
The new Adventure in the LoloCraft IV Mod! Take all your stuff and jump into the world of Minecraft LoloCraft IV!
'''

[[dependencies.lolocraftiv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




