modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraftiv"
version="Alpha 0.0.1"
displayName="LoloCraftIV"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mclolocraft.jimdosite.com/LoloCraftIV"
logoFile="logo.png"
authors="DerLoloHD and TheXBOXPlayz"
description='''
The New Adventure in a new LoloCraft Mod
'''

[[dependencies.lolocraftiv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




