modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraftiv"
version="1.1.8"
displayName="LoloCraftIV"
credits="2022 Copyright Fox Inc. Germany"
displayURL="https://mclolocraft.jimdofree.com/lolocraft-iv/"
logoFile="logo.png"
authors="DerLoloHD"
description='''
The New Adventure in a new LoloCraft Mod
'''

[[dependencies.lolocraftiv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




